---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-api-deployment
  labels:
    app: weather
spec:
  replicas: 3
  selector:
    matchLabels:
      app: weather
  template:
    metadata:
      labels:
        app: weather
    spec:
      containers:
        - name: weather
          image: [TODO: Replace with your own registry address]/weather-api:v3
          ports:
            - containerPort: 80
---
# Co-Pilot prompt:
# Create a Kubernetes service with an external load balancer that exposes the weather-api deployment on port 80
apiVersion: v1
kind: Service
metadata:
  name: weather-api-service
spec:
  type: LoadBalancer
  selector:
    app: weather
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
